# version: 2.1
# orbs:
#   webhook: circleci/webhook@1.1
# jobs:
#   build:
#     docker:
#       - image: circleci/node:10.16.0
#     working_directory: ~/repo
#     steps:
#       - checkout
#       - run: npm run test
#       - run: npm run deploy
#       - webhook/notify:
#           webhook_endpoint: $WEBHOOK_ENDPOINT
#           webhook_auth_token: $WEBHOOK_AUTH_TOKEN
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build

#       version: 2
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm run test
      - run: npm run deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
