name: 'Deploy'

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    environment:
      name: Production

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/checkout@v3.0.0
      - run: echo 'Hello'